# Generated by Django 5.0.7 on 2024-07-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTrackerApp', '0002_customuser_userprojectrole_delete_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
